// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqfqpnupsjfgrsloabhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZnFwbnVwc2pmZ3JzbG9hYmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Nzc1MjUsImV4cCI6MjA2NzE1MzUyNX0.xW2qkJa_j6n_JUX-SgzISde6d85mAQiEKevwHPjkIXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});